### ISSUE TITLE
Installation problem: font-loader-manifest not found

### ISSUE THREAD

**Issue by Phonetiker** [kamilmielnik/scrabble-solver#225]
I'm attempting to install scrabble-solver under Ubuntu Focal (20.04.5) with node version 16.19.1. No errors appear during installation with npm. However, when I launch the program at the command line, the browser opens with a page load error and I get the following error in the console (along with a stack trace, broadly indicating that npm failed on start):

Error: Cannot find module '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/.next/server/font-loader-manifest.json'

I have also tried:
1. npx scrabble-solver@latest
This yields the same page load error (no text to stdout/stderr)

2. installing nvm and installing it with more recent versions of npm
This yields slightly different but essentially parallel errors when I try to launch

Would appreciate any suggestions you might have. Thanks.

**Comment by kamilmielnik** [comment]
Thank you for reporting the issue!

I think I know what the problem is. I will release a new version shortly and let you know.

**Comment by kamilmielnik** [comment]
I've released `scrabble-solver@2.10.8`. Please try again and let me know if it works now :pray:

**Comment by Phonetiker** [comment]
Thanks for the response. Unfortunately I'm still getting the same errors. A few more details (in case they are relevant):
Browser: Firefox v110

When I check for the missing file with `find` in the shell it is not found in `/usr/lib/node_modules/scrabble-solver/`. 

I've also checked to make sure I don't have any network issues: my localhost settings seem ok--I'm able to view the nginx default localhost page (on a different port).  

I have tried uninstalling, deleting the config folder and reinstalling, but currently not finding any different result.

**Comment by Ark223** [comment]
Still getting the same error as described. Also your website is no longer working.

**Comment by kamilmielnik** [comment]
> I have tried uninstalling, deleting the config folder and reinstalling, but currently not finding any different result.

> Still getting the same error as described

I'll keep investigating.

> Also your website is no longer working.

It's up now. Thanks!

**Comment by kamilmielnik** [comment]
Works on Ubuntu 22.04 and Windows 10. 

> I'm attempting to install scrabble-solver under Ubuntu Focal (20.04.5) 

I'll try to set up a VM for Ubuntu 20.04.

**Comment by kamilmielnik** [comment]
> I'll try to set up a VM for Ubuntu 20.04.

I used a fresh Ubuntu 20.04 installation with nvm with node 16.19.1 and it worked.

> Still getting the same error as described. Also your website is no longer working.

@Ark223 what operating system did you use?

**Comment by kamilmielnik** [comment]
@Phonetiker, @Ark223 
Since I can't reproduce the issue, can you please post the entire error output that you get? :pray: 
If the outputs differ for different node versions it may help to share them as well.

**Comment by Phonetiker** [comment]
$ npm -v
9.5.1

$ node -v
v16.19.1

$ scrabble-solver 
Error: Cannot find module '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/.next/server/font-loader-manifest.json'
Require stack:
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/lib/start-server.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/cli/next-start.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/lib/commands.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.mod._resolveFilename (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at NextNodeServer.getFontLoaderManifest (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:643:16)
    at new Server (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:74:40)
    at new NextNodeServer (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:69:9)
    at NextServer.createServer (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js:147:16)
    at async /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js:159:31 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/lib/start-server.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/cli/next-start.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/lib/commands.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/bin/next'
  ]
}
ERROR: "start:app" exited with 1.
node:child_process:935
    throw err;
    ^

Error: Command failed: npm start
Error: Cannot find module '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/.next/server/font-loader-manifest.json'
Require stack:
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/lib/start-server.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/cli/next-start.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/lib/commands.js
- /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.mod._resolveFilename (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at NextNodeServer.getFontLoaderManifest (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:643:16)
    at new Server (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:74:40)
    at new NextNodeServer (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:69:9)
    at NextServer.createServer (/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js:147:16)
    at async /usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js:159:31 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/lib/start-server.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/cli/next-start.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/lib/commands.js',
    '/usr/lib/node_modules/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/bin/next'
  ]
}
ERROR: "start:app" exited with 1.

    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (/usr/lib/node_modules/scrabble-solver/bin/scrabble-solver.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(462) [Uint8Array] [
       10,  62,  32, 115,  99, 114,  97,  98,  98, 108, 101,  45,
      115, 111, 108, 118, 101, 114,  64,  50,  46,  49,  48,  46,
       56,  32, 115, 116,  97, 114, 116,  10,  62,  32, 110, 112,
      109,  45, 114, 117, 110,  45,  97, 108, 108,  32,  45,  45,
      112,  97, 114,  97, 108, 108, 101, 108,  32, 115, 116,  97,
      114, 116,  58,  42,  10,  10,  10,  62,  32, 115,  99, 114,
       97,  98,  98, 108, 101,  45, 115, 111, 108, 118, 101, 114,
       64,  50,  46,  49,  48,  46,  56,  32, 115, 116,  97, 114,
      116,  58,  98, 114,
      ... 362 more items
    ],
    Buffer(2668) [Uint8Array] [
       69, 114, 114, 111, 114,  58,  32,  67,  97, 110, 110, 111,
      116,  32, 102, 105, 110, 100,  32, 109, 111, 100, 117, 108,
      101,  32,  39,  47, 117, 115, 114,  47, 108, 105,  98,  47,
      110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101, 115,
       47, 115,  99, 114,  97,  98,  98, 108, 101,  45, 115, 111,
      108, 118, 101, 114,  47, 112,  97,  99, 107,  97, 103, 101,
      115,  47, 115,  99, 114,  97,  98,  98, 108, 101,  45, 115,
      111, 108, 118, 101, 114,  47,  46, 110, 101, 120, 116,  47,
      115, 101, 114, 118,
      ... 2568 more items
    ]
  ],
  pid: 95627,
  stdout: Buffer(462) [Uint8Array] [
     10,  62,  32, 115,  99, 114,  97,  98,  98, 108, 101,  45,
    115, 111, 108, 118, 101, 114,  64,  50,  46,  49,  48,  46,
     56,  32, 115, 116,  97, 114, 116,  10,  62,  32, 110, 112,
    109,  45, 114, 117, 110,  45,  97, 108, 108,  32,  45,  45,
    112,  97, 114,  97, 108, 108, 101, 108,  32, 115, 116,  97,
    114, 116,  58,  42,  10,  10,  10,  62,  32, 115,  99, 114,
     97,  98,  98, 108, 101,  45, 115, 111, 108, 118, 101, 114,
     64,  50,  46,  49,  48,  46,  56,  32, 115, 116,  97, 114,
    116,  58,  98, 114,
    ... 362 more items
  ],
  stderr: Buffer(2668) [Uint8Array] [
     69, 114, 114, 111, 114,  58,  32,  67,  97, 110, 110, 111,
    116,  32, 102, 105, 110, 100,  32, 109, 111, 100, 117, 108,
    101,  32,  39,  47, 117, 115, 114,  47, 108, 105,  98,  47,
    110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101, 115,
     47, 115,  99, 114,  97,  98,  98, 108, 101,  45, 115, 111,
    108, 118, 101, 114,  47, 112,  97,  99, 107,  97, 103, 101,
    115,  47, 115,  99, 114,  97,  98,  98, 108, 101,  45, 115,
    111, 108, 118, 101, 114,  47,  46, 110, 101, 120, 116,  47,
    115, 101, 114, 118,
    ... 2568 more items
  ]
}

**Comment by kamilmielnik** [comment]
I still have not managed to reproduce the problem :(

In the meantime I've upgraded Next.js (since errors are coming from Next.js) and all other dependencies.
I released `scrabble-solver@2.10.10` - there is a small chance it helped, please try :pray:

**Comment by Phonetiker** [comment]
With the Next.js upgrade it works! Thanks! Hopefully also the same result for @Ark223 Ark223.
